export const RECORD_ALL_REQUEST = 'RECORD_ALL_REQUEST'
export const RECORD_ALL_SUCCESS = 'RECORD_ALL_SUCCESS'
export const RECORD_ALL_FAIL= 'RECORD_ALL_FAIL'
export const RECORD_ALL_RESET= 'RECORD_ALL_RESET'