# Generated by Django 4.0.6 on 2022-08-03 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientAdditionalInfo',
        ),
    ]
