# Generated by Django 4.0.6 on 2022-10-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_profile_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='disorder',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
